/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand":         "#1e5a3c",
        "brand-mid":     "#2d7a50",
        "brand-light":   "#e8f5ee",
        "brand-border":  "#c8e6d4",
        "brand-dark":    "#143d28",
        "ink":           "#1a1a1a",
        "ink2":          "#444444",
        "ink3":          "#888888",
        "ink4":          "#bbbbbb",
        "bg":            "#ffffff",
        "bg2":           "#f7f6f3",
        "bg3":           "#f0ede8",
        "bg4":           "#e8f5ee",
        "border-light":  "rgba(0,0,0,0.07)",
        "border-mid":    "rgba(0,0,0,0.13)",
        "border-green":  "rgba(30,90,60,0.2)",
        "primary":           "#1e5a3c",
        "primary-container": "#1e5a3c",
        "on-primary":        "#ffffff",
        "on-primary-container": "#ffffff",
        "background":        "#ffffff",
        "surface":           "#ffffff",
        "surface-dim":       "#f7f6f3",
        "surface-bright":    "#ffffff",
        "surface-container-lowest": "#f0ede8",
        "surface-container-low":    "#f7f6f3",
        "surface-container":        "#f0ede8",
        "surface-container-high":   "#e8e8e6",
        "surface-container-highest":"#e0e0de",
        "surface-variant":   "#f0ede8",
        "on-surface":        "#1a1a1a",
        "on-surface-variant":"#666666",
        "on-background":     "#1a1a1a",
        "outline":           "#cccccc",
        "outline-variant":   "#e0e0e0",
        "secondary":         "#2d7a50",
        "secondary-container":"#e8f5ee",
        "on-secondary-container":"#1e5a3c",
        "error":             "#dc2626",
        "inverse-surface":   "#1a1a1a",
        "inverse-on-surface":"#ffffff",
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body:     ['"Manrope"', 'system-ui', 'sans-serif'],
        label:    ['"Manrope"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:  '0.375rem',
        md:  '0.5rem',
        lg:  '0.75rem',
        xl:  '1rem',
        full:'9999px',
      },
      animation: {
        'marquee': 'marquee 28s linear infinite',
        'fade-up': 'fadeUp 0.8s ease both',
        'blink':   'blink 1.5s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          from:{ transform:'translateX(0)' },
          to:  { transform:'translateX(-50%)' },
        },
        fadeUp: {
          from:{ opacity:0, transform:'translateY(20px)' },
          to:  { opacity:1, transform:'translateY(0)' },
        },
        blink: {
          '0%,100%':{ opacity:1 },
          '50%':    { opacity:0.2 },
        },
      },
    },
  },
  plugins: [],
}